# Generated by Django 5.1.4 on 2024-12-28 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='coauthored_books', to='books.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='main_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_books', to='books.author'),
            preserve_default=False,
        ),
    ]
